import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});

const josefinSans = localFont({
  src: [
    {
      path: './fonts/josefin/JosefinSans-Regular.ttf',
      weight: '400',
    },
    {
      path: './fonts/josefin/JosefinSans-Medium.ttf',
      weight: '500',
    },
    {
      path: './fonts/josefin/JosefinSans-SemiBold.ttf',
      weight: '600',
    },
    {
      path: './fonts/josefin/JosefinSans-Bold.ttf',
      weight: '700',
    },
  ],
  variable: "--font-josefin-sans",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${josefinSans.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
